$root = Split-Path -Parent $PSScriptRoot
$validator = Join-Path $PSScriptRoot 'validate_records.ps1'
$tmp = Join-Path $env:TEMP ('project-evolution-contracts-' + [guid]::NewGuid().ToString())
New-Item -ItemType Directory -Force $tmp | Out-Null
$now = (Get-Date).ToUniversalTime().ToString('o')
function Check($obj,$type) { $path=Join-Path $tmp "$type.json"; $obj | ConvertTo-Json -Depth 12 | Set-Content $path -Encoding UTF8; & $validator -RecordPath $path -Type $type | Out-Null }
Check ([ordered]@{id='purpose-demo-project';schemaVersion=1;projectId='demo-project';targetUsers=@('target user');coreProblem=@{statement='test';evidenceRefs=@()};coreJobs=@(@{jobId='job-core';task='complete task';successDefinition='done'});successIndicators=@(@{indicatorId='task-success';definition='task completes';unit='rate'});createdAt=$now;updatedAt=$now}) PurposeModel
Check ([ordered]@{id='profile-demo-project';schemaVersion=1;projectId='demo-project';projectType='web';language='javascript';framework='vite';runtime='node';deployment='local';server='absent';database='unknown';capabilities=@{login='unknown'};adapterStatus='ready';createdAt=$now;updatedAt=$now}) ProjectProfile
Check ([ordered]@{id='feature-map-demo-project';schemaVersion=1;projectId='demo-project';features=@([ordered]@{featureId='feature-core';name='core';jobIds=@('job-core');exists='yes';availability='unknown';usability='unknown';maturity='unknown';evidenceRefs=@();referenceRefs=@();knownGaps=@('needs user task')});createdAt=$now;updatedAt=$now}) FeatureMap
Check ([ordered]@{id='feedback-demo-001';schemaVersion=1;projectId='demo-project';sourceType='owner';sourceRef=$null;summary='test';rawContentRef=$null;receivedAt=$now;userJobIds=@();frequency='one_off';impact='low';evidenceStatus='unverified';privacyClass='internal';redactionStatus='not_needed';createdAt=$now;updatedAt=$now}) Feedback
Check ([ordered]@{id='opportunity-demo-001';schemaVersion=1;projectId='demo-project';userProblem='test';unmetNeed='test';affectedJobs=@('job-core');purposeLink='purpose-demo-project';evidenceRefs=@();referenceRefs=@();expectedValue='medium';costBand='low';complexityRisk='low';valueAssessment=$null;status='candidate';createdAt=$now;updatedAt=$now}) Opportunity
Check ([ordered]@{id='hypothesis-demo-001';schemaVersion=1;projectId='demo-project';opportunityId='opportunity-demo-001';statement='test';changeProposal='test';affectedJobs=@('job-core');participantType='owner';baseline=@{metrics=@(@{indicatorId='task-success';value='unknown';unit='rate';collectionMethod='manual';sampleDescription='none';sampleSize=0;collectedAt=$now})};target=@{expectedChange='improve';passCondition='same task succeeds';failCondition='task fails'};observationWindow='next run';sideEffectsToCheck=@();rollbackPlan='revert';status='proposed';createdAt=$now;updatedAt=$now}) Hypothesis
Check ([ordered]@{id='evidence-demo-001';schemaVersion=1;projectId='demo-project';type='user_task';source='user';capturedAt=$now;relatedJobIds=@();relatedHypothesisIds=@();evidenceLevel='L3';artifactRefs=@();repeatability='repeatable';participantType='target_user';dataClass='anonymized';confidence='medium';status='valid';createdAt=$now;updatedAt=$now}) Evidence
Check ([ordered]@{id='decision-demo-001';schemaVersion=1;projectId='demo-project';subjectId='opportunity-demo-001';decision='defer';decidedBy='user';decidedAt=$now;reason='later';allowedScope=$null;nextReviewAt=$now;monitorUntil=$null;createdAt=$now;updatedAt=$now}) Decision
Check ([ordered]@{id='research-source-demo-001';schemaVersion=1;title='Test';site='example';url='https://example.com/source';publishedAt=$null;queriedAt=$now;summary='test';useFor='comparison';credibility='medium';createdAt=$now;updatedAt=$now}) ResearchSource
Check ([ordered]@{id='research-conclusion-demo-001';schemaVersion=1;projectId='demo-project';researchGoal='test';sourceRefs=@('research-source-demo-001');supportsOpportunityIds=@();supportsHypothesisIds=@();adoptedConclusion='insufficient';rejectedConclusions=@();conclusionStatus='insufficient';applicability='demo';validUntil=$null;createdAt=$now;updatedAt=$now}) ResearchConclusion
Check ([ordered]@{runId='run-demo-001';schemaVersion=1;projectId='demo-project';mode='quick_review';startedAt=$now;finishedAt=$now;currentState='awaiting-user-decision';scope=@{jobs=@();modules=@();excluded=@()};evidenceRefs=@();findingIds=@();opportunityIds=@();hypothesisIds=@();decisionIds=@();blockedItems=@();stopReason='user_decision_required'}) RunResult
$bad = Join-Path $tmp 'bad.json'; ([ordered]@{id='evidence-demo-bad';schemaVersion=1;projectId='demo-project';type='user_task';source='user';capturedAt=$now;relatedJobIds=@();relatedHypothesisIds=@();evidenceLevel='L3';artifactRefs=@();repeatability='repeatable';participantType='target_user';dataClass='anonymized';confidence='medium';status='valid';createdAt=$now;updatedAt=$now;unexpected='reject'}) | ConvertTo-Json | Set-Content $bad -Encoding UTF8
$rejected=$false; try { & $validator -RecordPath $bad -Type Evidence | Out-Null } catch { $rejected=$true }; if (-not $rejected) { throw 'Unknown top-level field was accepted.' }
Write-Output 'PASS all contract samples and negative checks'
